config/routes.rb
ServiceCall::Application.routes.draw do
  devise_for :users

  resources :branches

  resources :inquiries

  resources :services

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  
  root :to => "services#index"

  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/branch.rb
class Branch < ActiveRecord::Base
  has_many :services
end

app/models/inquiry.rb
class Inquiry < ActiveRecord::Base
end

app/models/notifier.rb
class Notifier < ActionMailer::Base
  default :from => "any_from_address@example.com"

  # send a signup email to the user, pass in the user object that contains the user's email address
  def signup_email(user)
    mail( :to => user.email,
          :subject => "Thanks for signing up" )
  end
end

app/models/service.rb
class Service < ActiveRecord::Base

  validates :company,
            :address,
            :contact_person,
            :contact_number,
            :complain,
            :e_mail,
            :warranty,
            :branch_id, :presence => true


  #validates :status, :inclusion => { :in => [STATUS_PENDING], :message => "You need to pick one status." }


  STATUS_PENDING = 'PENDING'
  STATUS_COMPLETED  = 'COMPLETED'
  STATUS_COLLECTION = 'FOR COLLECTION'

  belongs_to :branch
   class << self
      def status_collection
       {
        "PENDING" => STATUS_PENDING,
        "FOR COLLECTION" => STATUS_COLLECTION,
        "COMPLETE" => STATUS_COMPLETED,
       }
      end
   end
    def status_tag
        case self.status
          when STATUS_PENDING then :error
          when STATUS_COLLECTION then :warning
          when STATUS_COMPLETED then :ok
        end
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/branches_controller.rb
class BranchesController < InheritedResources::Base
end

app/controllers/inquiries_controller.rb
class InquiriesController < InheritedResources::Base
end

app/controllers/services_controller.rb
class ServicesController < InheritedResources::Base
  before_filter :authenticate_user!

  def index
     @services = Service.order("").page(params[:page]).per(15)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/branches/_form.html.erb
<%= semantic_form_for(@branch) do |f| %>
  <%= f.inputs do %>
  <%= f.input :name %>
<% end %>
  <%= f.buttons  %>
<% end %>

app/views/branches/edit.html.erb
<h1>Editing branch</h1>

<%= render 'form' %>

<%= link_to 'Show', @branch %> |
<%= link_to 'Back', branches_path %>

app/views/branches/index.html.erb
<h1>Listing branches</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @branches.each do |branch| %>
  <tr>
    <td><%= branch.name %></td>
    <td><%= link_to 'Show', branch %></td>
    <td><%= link_to 'Edit', edit_branch_path(branch) %></td>
    <td><%= link_to 'Destroy', branch, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Branch', new_branch_path %>

app/views/branches/new.html.erb
<h1>New branch</h1>

<%= render 'form' %>

<%= link_to 'Back', branches_path %>

app/views/branches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @branch.name %>
</p>


<%= link_to 'Edit', edit_branch_path(@branch) %> |
<%= link_to 'Back', branches_path %>

app/views/inquiries/_form.html.erb
<%= form_for(@inquiry) do |f| %>
  <% if @inquiry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inquiry.errors.count, "error") %> prohibited this inquiry from being saved:</h2>

      <ul>
      <% @inquiry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :company %><br />
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :contact_person %><br />
    <%= f.text_field :contact_person %>
  </div>
  <div class="field">
    <%= f.label :contact_number %><br />
    <%= f.text_field :contact_number %>
  </div>
  <div class="field">
    <%= f.label :e_mail %><br />
    <%= f.text_field :e_mail %>
  </div>
  <div class="field">
    <%= f.label :inquiry %><br />
    <%= f.text_area :inquiry %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inquiries/edit.html.erb
<h1>Editing inquiry</h1>

<%= render 'form' %>

<%= link_to 'Show', @inquiry %> |
<%= link_to 'Back', inquiries_path %>

app/views/inquiries/index.html.erb
<h1>Listing inquiries</h1>

<table>
  <tr>
    <th>Company</th>
    <th>Address</th>
    <th>Contact person</th>
    <th>Contact number</th>
    <th>E mail</th>
    <th>Inquiry</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @inquiries.each do |inquiry| %>
  <tr>
    <td><%= inquiry.company %></td>
    <td><%= inquiry.address %></td>
    <td><%= inquiry.contact_person %></td>
    <td><%= inquiry.contact_number %></td>
    <td><%= inquiry.e_mail %></td>
    <td><%= inquiry.inquiry %></td>
    <td><%= link_to 'Show', inquiry %></td>
    <td><%= link_to 'Edit', edit_inquiry_path(inquiry) %></td>
    <td><%= link_to 'Destroy', inquiry, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Inquiry', new_inquiry_path %>

app/views/inquiries/new.html.erb
<h1>New inquiry</h1>

<%= render 'form' %>

<%= link_to 'Back', inquiries_path %>

app/views/inquiries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Company:</b>
  <%= @inquiry.company %>
</p>

<p>
  <b>Address:</b>
  <%= @inquiry.address %>
</p>

<p>
  <b>Contact person:</b>
  <%= @inquiry.contact_person %>
</p>

<p>
  <b>Contact number:</b>
  <%= @inquiry.contact_number %>
</p>

<p>
  <b>E mail:</b>
  <%= @inquiry.e_mail %>
</p>

<p>
  <b>Inquiry:</b>
  <%= @inquiry.inquiry %>
</p>


<%= link_to 'Edit', edit_inquiry_path(@inquiry) %> |
<%= link_to 'Back', inquiries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ServiceCall</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>


</body>
</html>

app/views/services/_form.html.erb
<div id="form1">
<br />
<br />
<div id="link1">
<%= link_to 'listing Service', services_path %>||
<%= link_to 'Create New Service', new_service_path %>
</div>
<div id="link">
<%= link_to "Sign out",  destroy_user_session_path,  :method=> :delete %> ||
<%= current_user.email if user_signed_in? %>
</div>
<br />
<br />
<%= semantic_form_for(@service) do |f| %>
  <%= f.inputs "New Service" do %>
  <%= f.input :branch, :include_blank => false %>
  <%= f.input :company %>
  <%= f.input :address %>
  <%= f.input :contact_person %>
  <%= f.input :contact_number, :label => "Any Contact Number" %> 
  <%= f.input :e_mail, :label => "Email Address" %>
  <%= f.input :complain, :input_html => { :rows => 4 } %>
  <%= f.input :warranty, :collection => [["Out of Warranty","Out of Warranty"], ["Under Warranty","Under Warranty"]], :as => :radio %>
  <%= f.input :notes, :input_html => { :rows => 4 }, :label => "Terms & Condition" %>
  <%= f.input :status, :collection => Service.status_collection, :include_blank => false, :wrapper_html => { :style => "display:none;" } %>
  <%= f.input :prepared_by,  :collection => [["- Auto Generated -","  ",current_user.email]], :wrapper_html => { :style => "display:none;" }, :include_blank => false %>
  <% end %>

 <%= f.buttons %>
<% end %>
</div>

 

app/views/services/edit.html.erb
<h1>Editing service</h1>

<%= render 'form' %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

app/views/services/index.html.erb
<div id="form1">
<br />
<br />
<div id="link1">
<%= link_to 'listing Service', services_path %>||
<%= link_to 'Create New Service', new_service_path %>
</div>
<div id="link">
<%= link_to "Sign out",  destroy_user_session_path,  :method=> :delete %> ||
<%= current_user.email if user_signed_in? %>
</div>
<br />
<br />
<table>
  <tr>
    <th>Company</th>
   
    <th>Contact person</th>
   
    <th>Prepared by</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @services.each do |service| %>
  <tr>
    <td><%= service.company %></td>
   
    <td><%= service.contact_person %></td>
   
    <td><%= service.prepared_by %></td>
    <td><%= service.status %></td>
    <td><%= link_to 'Preview', service %></td>
    <!--<td><%= link_to 'Edit', edit_service_path(service) %></td>
    <td><%= link_to 'Destroy', service, :confirm => 'Are you sure?', :method => :delete %></td>-->
  </tr>
<% end %>
</table>
<br />
<center><%= paginate @services %></center>
</div>

app/views/services/new.html.erb
<h1>New service</h1>

<%= render 'form' %>

<%= link_to 'Back', services_path %>

app/views/services/show.html.erb
<div id="form1">
	<br />
	<br />
	<div id="link1">
	<%= link_to 'listing Service', services_path %>||
	<%= link_to 'Create New Service', new_service_path %>
	</div>
<div id="link">
	<%= link_to "Sign out",  destroy_user_session_path,  :method=> :delete %> ||
	<%= current_user.email if user_signed_in? %>
</div>
	<br />
	<br />
<p id="notice"><%= notice %></p>
<h4>
  <b>Date Created:</b>
  <i><%= @service.created_at %></i>
</h4>
<h4>
  <b>COMPANY:</b>
  <i><%= @service.company %></i>
</h4>

<h4>
  <b>ADDRESS:</b>
  <i><%= @service.address %></i>
</h4>

<h4>
  <b>CONTACT PERSON:</b>
  <i><%= @service.contact_person %></i>
</h4>

<h4>
  <b>CONTACT NUMBER:</b>
  <i><%= @service.contact_number %></i>
</h4>

<h4>
  <b>EMAIL:</b>
  <i><%= @service.e_mail %></i>
</h4>

<h4>
  <b>WARRANTY NOTICE:</b>
  <i><%= @service.warranty %></i>
</h4>

<h4>
  <b>TERMS AND CONDITION:</b>
  <i><%= @service.notes %></i>
</h4>

<h4>
  <b>Complain:</b>
  <i><%= @service.complain %></i>
</h4>
<h4>
  <b>Date Completed:</b>
  <i><%= @service.updated_at %></i>
</h4>

</div>